(define (tree-map proc tree)
  (if (null? tree)
      '()
      (let ((first (car tree))
            (rest (cdr tree)))
        (cons (if (pair? first)
                  (tree-map proc first)
                  (proc first))
              (tree-map proc rest)))))
