(define (make-account balance secret-password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (desposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch password m)
    (if (equal? password secret-password)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'desposit) desposit)
              (else (error "Unknow request: MAKE-ACCOUNT" m)))
        (lambda (x) "Incorrect password")))
  dispatch)
