(define (call-the-cops x) "Has called the cops")

(define (make-account balance secret-password)
  (let ((incorrectCount 0)
        (limit 7))
      (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (desposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch password m)
    (if (equal? password secret-password)
        (begin (set! incorrectCount 0)
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'desposit) desposit)
                     (else (error "Unknow request: MAKE-ACCOUNT" m))))
        (if (< incorrectCount (- limit 1))
            (begin (set! incorrectCount (+ incorrectCount 1))
                   (lambda (x) "Incorrect password"))
            call-the-cops)))
  dispatch))
