(define (square x)
  (* x x))
(define (sum-of-squares x y)
  (+ (square x) (square y)))
(define (sum-of-the-squares-of-the-two-larger x y z)
  (if (> x y)
      (if (> y z) (sum-of-squares x y) (sum-of-squares x z))
      (if (> x z) (sum-of-squares x y) (sum-of-squares y z))))
